<?php

namespace AppBundle\Repository;

/**
 * ConceptsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptsRepository extends \Doctrine\ORM\EntityRepository
{
}
